/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as reentrancyAttackerSol from './ReentrancyAttacker.sol/index.js';
export type { reentrancyAttackerSol };