/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CredentialRegistryInterface extends Interface {
    getFunction(nameOrSignature: "CREDENTIAL_ISSUER_ADMIN_ROLE" | "CREDENTIAL_ISSUER_ROLE" | "DEFAULT_ADMIN_ROLE" | "credentials" | "getRoleAdmin" | "getValidLevel" | "grantRole" | "hasRole" | "isCredentialValid" | "issueCredential" | "renounceRole" | "revokeCredential" | "revokeRole" | "supportsInterface"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CredentialIssued" | "CredentialRevoked" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'CREDENTIAL_ISSUER_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'CREDENTIAL_ISSUER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'credentials', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getValidLevel', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isCredentialValid', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'issueCredential', values: [AddressLike, BytesLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeCredential', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'CREDENTIAL_ISSUER_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CREDENTIAL_ISSUER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'credentials', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getValidLevel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isCredentialValid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'issueCredential', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeCredential', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
  }

  
    export namespace CredentialIssuedEvent {
      export type InputTuple = [subject: AddressLike, credentialType: BytesLike, level: BigNumberish, issuedAt: BigNumberish, expiresAt: BigNumberish, version: BigNumberish, issuer: AddressLike];
      export type OutputTuple = [subject: string, credentialType: string, level: bigint, issuedAt: bigint, expiresAt: bigint, version: bigint, issuer: string];
      export interface OutputObject {subject: string, credentialType: string, level: bigint, issuedAt: bigint, expiresAt: bigint, version: bigint, issuer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CredentialRevokedEvent {
      export type InputTuple = [subject: AddressLike, credentialType: BytesLike, version: BigNumberish, revoker: AddressLike];
      export type OutputTuple = [subject: string, credentialType: string, version: bigint, revoker: string];
      export interface OutputObject {subject: string, credentialType: string, version: bigint, revoker: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CredentialRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): CredentialRegistry;
    waitForDeployment(): Promise<this>;

    interface: CredentialRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    CREDENTIAL_ISSUER_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    CREDENTIAL_ISSUER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    credentials: TypedContractMethod<
      [arg0: AddressLike, arg1: BytesLike, ],
      [[boolean, boolean, bigint, bigint, bigint, bigint, string] & {exists: boolean, revoked: boolean, level: bigint, issuedAt: bigint, expiresAt: bigint, version: bigint, issuer: string }],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getValidLevel: TypedContractMethod<
      [subject: AddressLike, credType: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isCredentialValid: TypedContractMethod<
      [subject: AddressLike, credType: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    issueCredential: TypedContractMethod<
      [subject: AddressLike, credType: BytesLike, level: BigNumberish, expiresAt: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeCredential: TypedContractMethod<
      [subject: AddressLike, credType: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'CREDENTIAL_ISSUER_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'CREDENTIAL_ISSUER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'credentials'): TypedContractMethod<
      [arg0: AddressLike, arg1: BytesLike, ],
      [[boolean, boolean, bigint, bigint, bigint, bigint, string] & {exists: boolean, revoked: boolean, level: bigint, issuedAt: bigint, expiresAt: bigint, version: bigint, issuer: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getValidLevel'): TypedContractMethod<
      [subject: AddressLike, credType: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isCredentialValid'): TypedContractMethod<
      [subject: AddressLike, credType: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'issueCredential'): TypedContractMethod<
      [subject: AddressLike, credType: BytesLike, level: BigNumberish, expiresAt: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeCredential'): TypedContractMethod<
      [subject: AddressLike, credType: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'CredentialIssued'): TypedContractEvent<CredentialIssuedEvent.InputTuple, CredentialIssuedEvent.OutputTuple, CredentialIssuedEvent.OutputObject>;
getEvent(key: 'CredentialRevoked'): TypedContractEvent<CredentialRevokedEvent.InputTuple, CredentialRevokedEvent.OutputTuple, CredentialRevokedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;

    filters: {
      
      'CredentialIssued(address,bytes32,uint8,uint64,uint64,uint32,address)': TypedContractEvent<CredentialIssuedEvent.InputTuple, CredentialIssuedEvent.OutputTuple, CredentialIssuedEvent.OutputObject>;
      CredentialIssued: TypedContractEvent<CredentialIssuedEvent.InputTuple, CredentialIssuedEvent.OutputTuple, CredentialIssuedEvent.OutputObject>;
    

      'CredentialRevoked(address,bytes32,uint32,address)': TypedContractEvent<CredentialRevokedEvent.InputTuple, CredentialRevokedEvent.OutputTuple, CredentialRevokedEvent.OutputObject>;
      CredentialRevoked: TypedContractEvent<CredentialRevokedEvent.InputTuple, CredentialRevokedEvent.OutputTuple, CredentialRevokedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    
    };
  }