/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MultiSigAdminInterface extends Interface {
    getFunction(nameOrSignature: "REQUIRED_CONFIRMATIONS" | "SIGNER_COUNT" | "confirmAndExecute" | "getProposal" | "hasConfirmed" | "isSigner" | "proposalCount" | "proposals" | "propose" | "signers"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ProposalConfirmed" | "ProposalCreated" | "ProposalExecuted"): EventFragment;

    encodeFunctionData(functionFragment: 'REQUIRED_CONFIRMATIONS', values?: undefined): string;
encodeFunctionData(functionFragment: 'SIGNER_COUNT', values?: undefined): string;
encodeFunctionData(functionFragment: 'confirmAndExecute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProposal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasConfirmed', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isSigner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'proposalCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'propose', values: [BigNumberish, AddressLike, BytesLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'signers', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'REQUIRED_CONFIRMATIONS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SIGNER_COUNT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmAndExecute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProposal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasConfirmed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isSigner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposalCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'propose', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'signers', data: BytesLike): Result;
  }

  
    export namespace ProposalConfirmedEvent {
      export type InputTuple = [proposalId: BigNumberish, confirmer: AddressLike, confirmationCount: BigNumberish];
      export type OutputTuple = [proposalId: bigint, confirmer: string, confirmationCount: bigint];
      export interface OutputObject {proposalId: bigint, confirmer: string, confirmationCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalCreatedEvent {
      export type InputTuple = [proposalId: BigNumberish, actionType: BigNumberish, target: AddressLike, role: BytesLike, subject: AddressLike, assetId: BigNumberish, proposer: AddressLike];
      export type OutputTuple = [proposalId: bigint, actionType: bigint, target: string, role: string, subject: string, assetId: bigint, proposer: string];
      export interface OutputObject {proposalId: bigint, actionType: bigint, target: string, role: string, subject: string, assetId: bigint, proposer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalExecutedEvent {
      export type InputTuple = [proposalId: BigNumberish, actionType: BigNumberish];
      export type OutputTuple = [proposalId: bigint, actionType: bigint];
      export interface OutputObject {proposalId: bigint, actionType: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MultiSigAdmin extends BaseContract {
    
    connect(runner?: ContractRunner | null): MultiSigAdmin;
    waitForDeployment(): Promise<this>;

    interface: MultiSigAdminInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    REQUIRED_CONFIRMATIONS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SIGNER_COUNT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    confirmAndExecute: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getProposal: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [[bigint, string, string, string, bigint, string, boolean, bigint] & {actionType: bigint, target: string, role: string, subject: string, assetId: bigint, proposer: string, executed: boolean, confirmationCount: bigint }],
      'view'
    >
    

    
    hasConfirmed: TypedContractMethod<
      [proposalId: BigNumberish, signer: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isSigner: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    proposalCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    proposals: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, string, boolean, bigint] & {actionType: bigint, target: string, role: string, subject: string, assetId: bigint, proposer: string, executed: boolean, confirmationCount: bigint }],
      'view'
    >
    

    
    propose: TypedContractMethod<
      [actionType: BigNumberish, target: AddressLike, role: BytesLike, subject: AddressLike, assetId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    signers: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'REQUIRED_CONFIRMATIONS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SIGNER_COUNT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'confirmAndExecute'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getProposal'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [[bigint, string, string, string, bigint, string, boolean, bigint] & {actionType: bigint, target: string, role: string, subject: string, assetId: bigint, proposer: string, executed: boolean, confirmationCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'hasConfirmed'): TypedContractMethod<
      [proposalId: BigNumberish, signer: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isSigner'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'proposalCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proposals'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, string, boolean, bigint] & {actionType: bigint, target: string, role: string, subject: string, assetId: bigint, proposer: string, executed: boolean, confirmationCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'propose'): TypedContractMethod<
      [actionType: BigNumberish, target: AddressLike, role: BytesLike, subject: AddressLike, assetId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'signers'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;

    getEvent(key: 'ProposalConfirmed'): TypedContractEvent<ProposalConfirmedEvent.InputTuple, ProposalConfirmedEvent.OutputTuple, ProposalConfirmedEvent.OutputObject>;
getEvent(key: 'ProposalCreated'): TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
getEvent(key: 'ProposalExecuted'): TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;

    filters: {
      
      'ProposalConfirmed(uint256,address,uint8)': TypedContractEvent<ProposalConfirmedEvent.InputTuple, ProposalConfirmedEvent.OutputTuple, ProposalConfirmedEvent.OutputObject>;
      ProposalConfirmed: TypedContractEvent<ProposalConfirmedEvent.InputTuple, ProposalConfirmedEvent.OutputTuple, ProposalConfirmedEvent.OutputObject>;
    

      'ProposalCreated(uint256,uint8,address,bytes32,address,uint256,address)': TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
      ProposalCreated: TypedContractEvent<ProposalCreatedEvent.InputTuple, ProposalCreatedEvent.OutputTuple, ProposalCreatedEvent.OutputObject>;
    

      'ProposalExecuted(uint256,uint8)': TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;
      ProposalExecuted: TypedContractEvent<ProposalExecutedEvent.InputTuple, ProposalExecutedEvent.OutputTuple, ProposalExecutedEvent.OutputObject>;
    
    };
  }