/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ICredentialCheck, ICredentialCheckInterface } from "../../AssetNFT.sol/ICredentialCheck.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "subject",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "credType",
        "type": "bytes32"
      }
    ],
    "name": "getValidLevel",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "subject",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "credType",
        "type": "bytes32"
      }
    ],
    "name": "isCredentialValid",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ICredentialCheck__factory {
    static readonly abi = _abi;
    static createInterface(): ICredentialCheckInterface {
      return new Interface(_abi) as ICredentialCheckInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ICredentialCheck {
      return new Contract(address, _abi, runner) as unknown as ICredentialCheck;
    }
  }
  