/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IEthereumDIDRegistry, IEthereumDIDRegistryInterface } from "../../AssetNFT.sol/IEthereumDIDRegistry.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "identity",
        "type": "address"
      }
    ],
    "name": "identityOwner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IEthereumDIDRegistry__factory {
    static readonly abi = _abi;
    static createInterface(): IEthereumDIDRegistryInterface {
      return new Interface(_abi) as IEthereumDIDRegistryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IEthereumDIDRegistry {
      return new Contract(address, _abi, runner) as unknown as IEthereumDIDRegistry;
    }
  }
  