/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ITimeBoundAccessControl, ITimeBoundAccessControlInterface } from "../../AssetNFT.sol/ITimeBoundAccessControl.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "role",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "hasActiveRole",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ITimeBoundAccessControl__factory {
    static readonly abi = _abi;
    static createInterface(): ITimeBoundAccessControlInterface {
      return new Interface(_abi) as ITimeBoundAccessControlInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ITimeBoundAccessControl {
      return new Contract(address, _abi, runner) as unknown as ITimeBoundAccessControl;
    }
  }
  