/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IMultiSigAdmin, IMultiSigAdminInterface } from "../../../test/ReentrancyAttacker.sol/IMultiSigAdmin.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "proposalId",
        "type": "uint256"
      }
    ],
    "name": "confirmAndExecute",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IMultiSigAdmin__factory {
    static readonly abi = _abi;
    static createInterface(): IMultiSigAdminInterface {
      return new Interface(_abi) as IMultiSigAdminInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IMultiSigAdmin {
      return new Contract(address, _abi, runner) as unknown as IMultiSigAdmin;
    }
  }
  