/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMultiSigAdmin__factory } from './IMultiSigAdmin__factory.js';
export { MaliciousTarget__factory } from './MaliciousTarget__factory.js';