/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMultiSigAdmin } from './IMultiSigAdmin.js';
export type { MaliciousTarget } from './MaliciousTarget.js';